services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  huey:
    build:
      context: .
      dockerfile: source/Dockerfile
    env_file:
      - ./source/.env
    depends_on:
      - db
      - redis
    command: python3 manage.py run_huey
    restart: unless-stopped

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - .vloumes/db_data:/var/lid/postgres/data
    env_file:
      - ./source/.env
    restart: always

  web:
    build:
      context: .
      dockerfile: source/Dockerfile
    env_file:
      - ./source/.env
    ports:
      - "8001:8001"
    volumes:
      - ./source:/app
    restart: always
    depends_on:
      - db
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8001"