# Generated by Django 6.0.5 on 2026-06-24 13:35

from django.db import migrations

def set_required_statuses_to_articles(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    Article.objects.all().update(status='approved')


def rollback(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    Article.objects.filter(author="Автор 2").update(status='Return_for_revision')
    Article.objects.exclude(author="Автор 2").update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_article_blog_delete_blog'),
    ]

    operations = [
        migrations.RunPython(set_required_statuses_to_articles, rollback),
    ]
